p8105_hw2_yw4886
================
Yijia
2026-10-01

## Set up packages

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
```

# Problem 1

## Import and clean

``` r
transit_df =
  read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") |>
  janitor::clean_names() |>
  select(
    line,
    station_name,
    station_latitude,
    station_longitude,
    route1:route11,
    entry,
    vending,
    entrance_type,
    ada
  ) |>
  mutate(
    entry = case_match(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE
    )
  )
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

### Write a short paragraph about this dataset – explain briefly what variables the dataset contains, describe your data cleaning steps so far

The NYC Transit dataset contains information about subway station
entrances and exits, including station line and name, geographic
coordinates, routes served, entry status, vending availability, entrance
type, and ADA accessibility. I cleaned the data by standardizing the
variable names, selecting only the variables relevant to the analysis,
and converting the `entry` variable from character values (`YES` and
`NO`) to a logical variable (`TRUE` and `FALSE`).

### Give the dimension (rows x columns) of the resulting dataset

``` r
dim(transit_df)
```

    ## [1] 1868   19

The dataset has 1,868 observations and 19 variables.

### Are these data tidy?

At this stage, the data are not fully tidy because route information is
spread across multiple columns (route1 through route11) rather than
stored as values of a single route variable.

## Answer the following questions using these data

### How many distinct stations are there?

``` r
transit_df |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 465

### How many stations are ADA compliant?

``` r
transit_df |>
  filter(ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 84

### What proportion of station entrances / exits without vending allow entrance?

``` r
transit_df |>
  filter(vending == "NO") |>
  summarise(
    proportion = mean(entry,na.rm = TRUE)
  )
```

    ## # A tibble: 1 × 1
    ##   proportion
    ##        <dbl>
    ## 1      0.377

## Reformat data

``` r
transit_tidy =
  transit_df |>
  mutate(
    across(route1:route11, as.character))|>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name"
  ) |>
  drop_na(route_name) |>
  mutate(
    route_number = as.integer(route_number)
  )
transit_tidy
```

    ## # A tibble: 4,270 × 10
    ##    line     station_name station_latitude station_longitude entry vending
    ##    <chr>    <chr>                   <dbl>             <dbl> <lgl> <chr>  
    ##  1 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  2 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  3 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  4 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  5 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  6 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  7 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  8 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  9 4 Avenue 45th St                  40.6             -74.0 TRUE  YES    
    ## 10 4 Avenue 45th St                  40.6             -74.0 TRUE  YES    
    ## # ℹ 4,260 more rows
    ## # ℹ 4 more variables: entrance_type <chr>, ada <lgl>, route_number <int>,
    ## #   route_name <chr>

### How many distinct stations serve the A train?

``` r
transit_tidy |>
  filter(route_name == "A") |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 60

### Of the stations that serve the A train, how many are ADA compliant?

``` r
transit_tidy |>
  filter(
    route_name == "A",
    ada == TRUE
  ) |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 17

# Problem 2

### Read and clean the Mr. Trash Wheel sheet

``` r
mr_trash =
  read_excel(
    "./data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N709"
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    month = str_trim(month),
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr. Trash Wheel"
  )
mr_trash
```

    ## # A tibble: 707 × 15
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 697 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

### Professor Trash Wheel

``` r
professor_trash =
  read_excel(
    "./data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M134"
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    month = str_trim(month),
    trash_wheel = "Professor Trash Wheel"
  )
professor_trash
```

    ## # A tibble: 132 × 14
    ##    dumpster month     year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>    <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00        1.79                 15
    ##  2        2 January   2017 2017-01-30 00:00:00        1.58                 15
    ##  3        3 February  2017 2017-02-26 00:00:00        2.32                 18
    ##  4        4 February  2017 2017-02-26 00:00:00        3.72                 15
    ##  5        5 February  2017 2017-02-28 00:00:00        1.45                 15
    ##  6        6 March     2017 2017-03-30 00:00:00        1.71                 15
    ##  7        7 April     2017 2017-04-01 00:00:00        1.82                 15
    ##  8        8 April     2017 2017-04-20 00:00:00        2.37                 15
    ##  9        9 May       2017 2017-05-10 00:00:00        2.64                 15
    ## 10       10 May       2017 2017-05-26 00:00:00        2.78                 15
    ## # ℹ 122 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>, trash_wheel <chr>

## Gwynnda

``` r
gwynnda_trash =
  read_excel(
    "./data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynnda the Good Wheel of the W",
    range = "A2:L351"
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    month = str_trim(month),
    trash_wheel = "Gwynnda"
  )
gwynnda_trash
```

    ## # A tibble: 349 × 13
    ##    dumpster month   year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>  <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 July    2021 2021-07-03 00:00:00        0.93                 15
    ##  2        2 July    2021 2021-07-07 00:00:00        2.26                 15
    ##  3        3 July    2021 2021-07-07 00:00:00        1.62                 15
    ##  4        4 July    2021 2021-07-16 00:00:00        1.76                 15
    ##  5        5 July    2021 2021-07-30 00:00:00        1.53                 15
    ##  6        6 August  2021 2021-08-11 00:00:00        2.06                 15
    ##  7        7 August  2021 2021-08-14 00:00:00        1.9                  15
    ##  8        8 August  2021 2021-08-16 00:00:00        2.16                 15
    ##  9        9 August  2021 2021-08-16 00:00:00        2.6                  15
    ## 10       10 August  2021 2021-08-17 00:00:00        3.21                 15
    ## # ℹ 339 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>, trash_wheel <chr>

## Combine

``` r
trash_wheel_df =
  bind_rows(
    mr_trash,
    professor_trash,
    gwynnda_trash
  )
trash_wheel_df
```

    ## # A tibble: 1,188 × 15
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 1,178 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

## Answers and Discussion

### For available data, what was the total weight of trash collected by Professor Trash Wheel?

``` r
professor_weight =
  trash_wheel_df |>
  filter(trash_wheel == "Professor Trash Wheel") |>
  summarize(
    total_weight = sum(weight_tons, na.rm = TRUE)
  ) |>
  pull(total_weight)
professor_weight
```

    ## [1] 282.26

### What was the total number of cigarette butts collected by Gwynnda in June of 2022?

``` r
gwynnda_cigarettes =
  trash_wheel_df |>
  filter(
    trash_wheel == "Gwynnda",
    year == 2022,
    month == "June"
  ) |>
  summarize(
    total_cigarettes = sum(cigarette_butts, na.rm = TRUE)
  ) |>
  pull(total_cigarettes)
gwynnda_cigarettes
```

    ## [1] 18120

## Write a paragraph about these data; you are encouraged to use inline R. Be sure to note the number of observations in the resulting dataset, and give examples of key variables.

The combined Trash Wheel dataset contains 1188 observations from
Mr. Trash Wheel, Professor Trash Wheel, and Gwynnda. Key variables
include dumpster number, month and year of collection, date, weight and
volume of trash collected, and counts of different types of trash such
as plastic bottles, polystyrene, cigarette butts, plastic bags, and
wrappers. During data cleaning, I imported each worksheet using
specified Excel ranges to exclude non-data rows and columns,
standardized the variable names, removed rows without dumpster-specific
information, cleaned the month and year variables, and rounded the
number of sports balls in the Mr. Trash Wheel dataset to the nearest
integer. I also created a `trash_wheel` variable to identify which Trash
Wheel each observation came from before combining the three datasets.
Professor Trash Wheel collected a total of 282.26 tons of trash, and
Gwynnda collected 1.812^{4} cigarette butts in June 2022.

# Problem 3

## Import and clean baseline demographics

``` r
mci_baseline =
  read_csv(
    "./data/data_mci/data_mci/MCI_baseline.csv",
    skip = 1,
    na = c(".", "NA")
  ) |>
  janitor::clean_names() |>
  rename(
    age = current_age,
    age_onset = age_at_onset
  ) |>
  mutate(
    sex = case_match(
      sex,
      0 ~ "Female",
      1 ~ "Male"
    ),
    apoe4 = case_match(
      apoe4,
      0 ~ "Non-carrier",
      1 ~ "Carrier"
    )
  ) |>
  filter(
    is.na(age_onset) | age_onset > age
  )
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

## Answer to questions and Discussion

### How many participants were recruited?

``` r
nrow(mci_baseline)
```

    ## [1] 479

### How many developed MCI?

``` r
mci_baseline |>
  summarize(
    developed_mci = sum(!is.na(age_onset))
  )
```

    ## # A tibble: 1 × 1
    ##   developed_mci
    ##           <int>
    ## 1            93

### Average baseline age

``` r
mci_baseline |>
  summarize(
    mean_age = mean(age)
  )
```

    ## # A tibble: 1 × 1
    ##   mean_age
    ##      <dbl>
    ## 1     65.0

### What proportion of women are APOE4 carriers?

``` r
mci_baseline |>
  filter(sex == "Female") |>
  summarize(
    prop_apoe4 = mean(apoe4 == "Carrier")
  )
```

    ## # A tibble: 1 × 1
    ##   prop_apoe4
    ##        <dbl>
    ## 1        0.3

### Baseline discussion

The cleaned baseline demographic dataset contains 479 participants. The
original file contained a descriptive first row, so I skipped this row
during import and treated `"."` and `"NA"` as missing values. I
standardized the variable names, recoded sex and APOE4 carrier status
from numeric codes into categorical variables, and removed participants
whose MCI onset age was less than or equal to their baseline age because
they did not meet the inclusion criterion of being MCI-free at baseline.
The dataset includes participant ID, baseline age, sex, years of
education, APOE4 carrier status, and age at MCI onset. Among the
included participants, 93 developed MCI during follow-up. The mean
baseline age was 65.03 years, and 30% of women were APOE4 carriers.

## Import and tidy amyloid data

``` r
mci_amyloid =
  read_csv(
    "./data/data_mci/data_mci/mci_amyloid.csv",
    skip = 1,
    na = "NA"
  ) |>
  janitor::clean_names() |>
  rename(id = study_id) |>
  pivot_longer(
    baseline:time_8,
    names_to = "visit",
    values_to = "amyloid"
  ) |>
  mutate(
    time = case_match(
      visit,
      "baseline" ~ 0,
      "time_2" ~ 2,
      "time_4" ~ 4,
      "time_6" ~ 6,
      "time_8" ~ 8
    )
  )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

## Comments and Answers

### Comment on the steps on the import process and the features of the dataset

The amyloid dataset contains longitudinal measurements of the amyloid
42/40 ratio at baseline and approximately 2, 4, 6, and 8 years after
baseline. As with the demographic dataset, I skipped the descriptive
first row during import and standardized the variable names. The
original data were in wide format, with each follow-up time stored in a
separate column, so I used `pivot_longer()` to create a tidy dataset
with one row per participant per visit. I also created a numeric `time`
variable representing years since baseline. The resulting dataset
contains 487 participants and 2435 participant-visit observations.

### Check participants appearing in only one dataset

#### Participants appearing only in the baseline dataset

``` r
baseline_ids =
  mci_baseline |>
  distinct(id) |>
  mutate(in_baseline = TRUE)

amyloid_ids =
  mci_amyloid |>
  distinct(id) |>
  mutate(in_amyloid = TRUE)

baseline_only =
  baseline_ids |>
  left_join(
    amyloid_ids,
    by = "id"
  ) |>
  filter(is.na(in_amyloid))

nrow(baseline_only)
```

    ## [1] 8

#### Participants appearing only in the amyloid dataset

``` r
amyloid_only =
  amyloid_ids |>
  left_join(
    baseline_ids,
    by = "id"
  ) |>
  filter(is.na(in_baseline))

nrow(amyloid_only)
```

    ## [1] 16

#### Comment on participants appearing in only one dataset

There were 8 participants who appeared only in the cleaned baseline
demographic dataset and 16 participants who appeared only in the amyloid
dataset. This shows that the sets of participant IDs are not identical
across the two datasets.

### Combine the demographic and biomarker datasets

``` r
mci_complete =
  mci_baseline |>
  inner_join(
    mci_amyloid,
    by = "id"
  )
write_csv(
  mci_complete,
  "./data/mci_complete.csv"
)
```

#### Description

The demographic and biomarker datasets were combined using
`inner_join()` by participant ID, so only participants who appeared in
both datasets were retained. The resulting dataset contains 471
participants and 2355 participant-visit observations. Each row
represents one participant at one study visit and includes baseline
demographic variables, such as age, sex, education, APOE4 carrier
status, and MCI onset information, together with visit time and the
corresponding amyloid 42/40 ratio.The combined dataset was exported as
`mci_complete.csv` to the data directory.
